membre maina
iTeam-S/iteam-s.github.io pull request #11
Opened 2021-01-07 14:38 UTC by Jayah001

@gaetan1903

2021-01-08 05:55 UTC, gaetan1903 commented
Salut,

Bon travail pour ton pull request.. 

J'ai juste des soucis,
J'ai vérifié le footer et c'est le bazar , 

donc je pense que c'est du au fait que tu as effacé les styles css du footer 
voir capture d'ecran : Pourquoi avoir effacé??

![image](https://user-images.githubusercontent.com/43904633/103979630-3ff31300-518f-11eb-8b48-1909f8f53696.png)

2021-01-08 06:03 UTC, gaetan1903 commented
@Jayah001 
Tu as voulu effacé le footer, 
je pense qu'il faut laisser le footer, 
c'est plutôt le contact qu'il faut effacer dans  la page membre...

etn'oublie pas que le css est partager par les pages , fait attention quand tu efface le css

2021-01-08 06:03 UTC, gaetan1903 requested changes
En attentte de ta mise à jour

2021-01-08 14:10 UTC, Jayah001 commented
Bonsoir @gaetan1903 , désolé pour le footer ಥ_ಥ,
 c'est reglé maintenant bb44d59😁👍

2021-01-09 07:10 UTC, gaetan1903 commented
Merci pour la maj

2021-01-09 07:10 UTC, gaetan1903 approved these changes

2021-01-09 07:10 UTC, merged